spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/logindemodb_prod
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    enabled: false

security:
  jwt:
    secret-key: somerandomkey
    issuer: https://spring-security-login.com
    validity-in-ms: 300000 # 5 minutes
    audience: client-app-name

users:
  admins:
    - username: admin1
      password: admin123
      firstName: Admin
      lastName: User1
  regulars:
